### ISSUE TITLE
euserv似乎手动过一次验证码就不出现了

### ISSUE THREAD

**Issue by pure69per** [kkkyg/EU666#3]
昨天手动过了一次，接下来4次都成功续期

by the way，这次验证码几乎无解了吧，为了过验证码脚本本身复杂度也会提高

**Comment by kkkyg** [comment]
> 昨天手动过了一次，接下来4次都成功续期
> 
> by the way，这次验证码几乎无解了吧，为了过验证码脚本本身复杂度也会提高

为什么我碰不到验证！！晕死！

**Comment by pure69per** [comment]
> > 昨天手动过了一次，接下来4次都成功续期
> > by the way，这次验证码几乎无解了吧，为了过验证码脚本本身复杂度也会提高
> 
> 为什么我碰不到验证！！晕死！

现在我又有了，看来是固定频率
